### ISSUE TITLE
Milestone and Future of ng-redux Discussion

### ISSUE THREAD

**Issue by AntJanus** [angular-redux/ng-redux#142]
Hi all,

I'm a new contributor on ng-redux and I'm taking over for @wbuchwalter on this repo. There are a few changes I'd like to implement and I want to use this issue to track them. If anyone has any input, I'm totally all for it and let's discuss it.

## 3.5.0 Milestone

Currently, the latest "version" of 3.4.0-beta.1 without any tags and release information. I'd like to release 3.4.0 ASAP and then brace for the final 3.X release: 3.5.0. What will be in this release (or will at least be considered):

- [x] deprecation notice for removing Bower support (will be removed in 4.0.0) (#151)
- [x] dispatch result return (#120)
- [x] remove unneeded $scope injection (#108)
- [x] copy over Symbol from Redux's `createStore` (#129, #144)
- [x] type definition fix (#114)
- [x] dependency updates (#150)
- [x] general doc updates/cleanup (#150)
- [x] npm scripts syntax that uses binaries directly (#146)
- [x] prepublish scripts + `.npmignore` (#150)

Other features/fixes:

- [x] set env to `production`

**Comment by deini** [comment]
Would love to see the ability to use ES6 classes for actions in the roadmap. https://github.com/angular-redux/ng-redux/issues/136

**Comment by AntJanus** [comment]
@deini do you know how Redux handles this type of situation? Or is this an ng-redux-only thing?

**Comment by deini** [comment]
Its more of a `ng-redux` thing, to be able to use Angular's injection in Action creators (eg: `$http`) you need to create a service that wrap those action creators.

If you make that wrapper service a Class, the `connect` doesn't work as expected, so right now we are using `functions` for those wrapper services, however its not ideal since all of our services are Classes with the exception of action creators wrappers. 

I can take investigate a bit more and give you more details / submit a PR.

**Comment by AntJanus** [comment]
@deini Ahhh, I see. Alright, yeah, if you can create a PR, let's shove it into a release right after 4.0.0, like a 4.1.0 I think that definitely makes sense.

@HunterEl if you can do code review and test some of the branches I reference, that'd be fantastic because then we can just merge that in and keep going.

**Comment by HunterEl** [comment]
@AntJanus Absolutely. Will do that this weekend.

**Comment by HunterEl** [comment]
@AntJanus, #120 Looks good and code-reviewed by me. Issue #180 from your comment should be #108, looks good. You've made a comment on #129. Let me know if there what else you would like to me to look at.

**Comment by HunterEl** [comment]
We should also get rid of the `unmaintained` header on the main readme. Would be bad to deter new people.

**Comment by AntJanus** [comment]
@HunterEl thanks for the hard work! I'm going to go ahead and do a release of the current beta and once that's done, merge everything you mentioned. We can wait for changes for a bit and I'll go ahead and start work on the 4.0.0 milestone.

Do you want to go ahead and become a collaborator? That way, your comments will carry the same weight and you can make direct changes/work on 4.0.0 as well.

**Comment by HunterEl** [comment]
@AntJanus My pleasure! And that would be great! Thank you.

**Comment by skortchmark9** [comment]
Glad to see this repo is becoming active again. It's been really great for keeping my state sane while maintaining a legacy app.

**Comment by rperrote** [comment]
I want to know more about testing.  I can not even run test with mock (https://gist.github.com/kareniel/ac08b1b4e7c817583da649452a8839fe)
