### ISSUE TITLE
4.0.0 Release Tracker

### ISSUE THREAD

**Issue by AntJanus** [angular-redux/ng-redux#164]
## 4.0.0 Milestone

The 4.0.0 release is supposed to be a breaking one. It should setup `ng-redux` to be more collaborator friendly and increase the pace of development. 

Staging branch is on #165 

What it will include:

### Dev friendliness

- [ ] full deprecation of Bower support (#165)
- [x] implementation of [standard-version](https://github.com/conventional-changelog/standard-version) for better releases, tagging, and changelog
- [x] implementation of [commitizen](https://github.com/commitizen/cz-cli) to encourage commit messages that standard-version can recognize
- [ ] CONTRIBUTING.md guidelines (#165)
- [x] new build chain -- fails on current NPM version (fixed in previous releases)
- [x] prepublish script to avoid 3.4.0 mishaps. (fixed in previous releases)

### Features

- [x] implement `provideStore` functionality akin to what `@angular-redux/store` has (#19)

The rest is TBD.

## 4.1.0 Milestone

- [ ] ES2015 for action (#136)
- [ ] compare prev and next state (#85)

**Comment by AntJanus** [comment]
I split this out from the previous issue so that it's easier to track the work.

**Comment by rajatvijay** [comment]
Hi

I am just starting to integrate this into one of my legacy application. So just wanted to know if this version is going to be a breaking on when will this be released, I mean sometime soon or late. Should I wait for this or just go ahead and use the current version.

**Comment by AntJanus** [comment]
@rajatvijay I haven't started any work on this yet. There shouldn't be any major breaking changes other than dropping bower support. If you need to use bower, only versions up to 3.5.2 will be supported.

I wouldn't wait around on it! :)
