### ISSUE TITLE
4.X.0 Discussion/Tracking Issue

### ISSUE THREAD

**Issue by AntJanus** [angular-redux/ng-redux#204]
I've been semi-MIA for the past few months -- you know how it is, personal life. But I'm back and it looks like we've got some serious stuff to work on and deploy!

4.1.0 will mainly be a bugfix/update milestone.

## Goals

- [ ] make ng-redux compatible with dev tools again (https://github.com/angular-redux/ng-redux/issues/196)
- [ ] update rollup config (https://github.com/angular-redux/ng-redux/issues/191)
- [ ] run TravisCI correctly (https://github.com/angular-redux/ng-redux/issues/193)
- [x] FINALLY resolve TypeScript issues (https://github.com/angular-redux/ng-redux/issues/177)
- [ ] update unsafe dependencies https://github.com/angular-redux/ng-redux/network/dependencies
- [x] update to redux 4 (https://github.com/angular-redux/ng-redux/pull/209)

## Progress

- [x] release Alpha with changes that happened between 4.0.3 and 4.1.0

**Comment by piehouserat** [comment]
Hey!

We just added redux-observable to our project which has a peer dependency on redux version 4 and so far so good - everything seems to be working correctly, however I'm eagerly awaiting an updated version of ng-redux that officially supports v4 mainly for my peace of mind.

Just wanted to personally thank you for the amazing work on this project - it's allowing us to move all our business logic out of angular services to vanilla js behind redux so that we can migrate to a different framework soon :)

Cheers,
Martin

**Comment by piehouserat** [comment]
@AntJanus following on from your message from the other issue - yes I would be very grateful if you could release a 4.1.0-alpha - the dev tools thing isn't really an issue for us as we use the logging middleware which suffices for now

**Comment by piehouserat** [comment]
Hi @AntJanus I'm hoping I can chase you a little on this one. I think the digest work will make a massive improvement to the performance of our application. Many thanks, Martin

**Comment by AntJanus** [comment]
@piehouserat alpha is out! :)

**Comment by piehouserat** [comment]
Any ETA on when a more formal release is expected? That provideStore stuff will be super useful for us as we're starting to port some of our components over to React and Redux in that world takes a vanilla store so would be great to extract out our store config and re-use it across both frameworks

**Comment by nobitagit** [comment]
@piehouserat if you need ProvideStore functionality that is in master already, you will be able to use it with your version already, as long as it's up to date. Check the readme for an example of its usage.

**Comment by piehouserat** [comment]
@nobitagit ah nice, I should have noticed it was just a commit to add the missing documentation, that functionality will be very useful and save me having to maintain two separate versions of the store

**Comment by AntJanus** [comment]
I decided to start releasing the updates piece-meal. There's no reason to hold up a release for a bunch of unrelated tasks
